name: Claude PR Action

permissions:
  contents: write
  pull-requests: write
  issues: write

on:
  issue_comment:
    types: [created]
  pull_request_review_comment:
    types: [created]
  issues:
    types: [opened, assigned]

jobs:
  claude-pr:
    if: contains(github.event.comment.body, '@claude')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Claude CLI
        run: npm install -g @anthropic-ai/claude-cli

      - name: Claude PR Action
        env:
          ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Extract the comment and context
          COMMENT="${{ github.event.comment.body }}"
          ISSUE_NUMBER="${{ github.event.issue.number || github.event.pull_request.number }}"
          
          # Remove @claude mention to get the actual request
          REQUEST=$(echo "$COMMENT" | sed 's/@claude//g' | xargs)
          
          echo "Processing request: $REQUEST"
          
          # Create a temporary file with the request
          echo "$REQUEST" > /tmp/claude_request.txt
          
          # Use Claude CLI to process the request
          claude code --no-interactive \
            --model claude-3-5-sonnet-20241022 \
            --context-repo . \
            --request-file /tmp/claude_request.txt \
            --output-format markdown > /tmp/claude_response.md
          
          # Post the response as a comment
          gh issue comment $ISSUE_NUMBER --body-file /tmp/claude_response.md

      - name: Create PR if needed
        if: contains(github.event.comment.body, 'create PR') || contains(github.event.comment.body, 'make changes')
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Check if changes were made
          if [ -n "$(git status --porcelain)" ]; then
            BRANCH_NAME="claude-$(date +%s)"
            git checkout -b $BRANCH_NAME
            git add .
            git commit -m "Changes requested by @claude
            
            Original request: ${{ github.event.comment.body }}"
            
            git push origin $BRANCH_NAME
            
            gh pr create \
              --title "Claude Code: Automated changes" \
              --body "This PR was automatically created by Claude Code in response to: ${{ github.event.comment.body }}" \
              --base main \
              --head $BRANCH_NAME
          fi